### ISSUE TITLE
How to use gitprompt

### ISSUE THREAD

**Issue by mathomp4** [cjuniet/dotfiles#1]
Mr Juniet,

I hope you don't mind the random issue call, but I've been searching for a way to get a good gitprompt while having to use tcsh. Some google-fu led to your github. I see you have a C and C++ code call gitprompt. How exactly does one go about using those?

Thanks,
Matt

**Comment by cjuniet** [comment]
Hello Matt, I'm truly sorry for the very late answer.
First, compile the C++ executable with: `CC -std=c++11 -o gitprompt gitprompt.cc`
Then, add this line to your .cshrc: `alias precmd 'set prompt="`gitprompt "%m:%~" "%#"` "'`
Like the standard git-prompt.sh, my gitprompt takes two parameters, pre and post, and displays `pre (branch flags) post`.
If you would like to change the colours, you will have to modify the main function and recompile.
